### ISSUE TITLE
Idea czy Eclipse? 

### ISSUE THREAD

**Issue by SemionPar** [SemionPar/application.allegro#1]
Osobiście wolę [Ideę](https://www.jetbrains.com/idea/download/), ale nie wszystkim się musi spodobać. Ma wbudowane wsparcie Gita, do Eclipsa zaś jest [wtyczka](http://www.vogella.com/tutorials/EclipseGit/article.html).
Zanim zaczniemy coś pisać, musimy się zdecydować z jakiego IDE będziemy korzystać, jak będą różne to projekt się zwyczajnie rozjedzie.

Ja głosuję za Ideą.

**Comment by MichalPi** [comment]
Nie uzywalem tej idei ale widze ze ogolnie interfejs sie nie rozni duzo od eclipsa takze nie widze problemu jak narazie zeby jej uzywac

**Comment by SemionPar** [comment]
Idea jest fajna, ma autosave'a :) No i np. Android Studio jest oparty właśnie na Idei. Próbowałem jeszcze NetBeansa, ale jakoś mi nie przypadł do gustu.

**Comment by Alemina** [comment]
Dla mnie może być Idea.

**Comment by crisdragon** [comment]
ja rownież jestem za idea

**Comment by SemionPar** [comment]
No to demokratycznie walczymy z Ideą ;)
