### ISSUE TITLE
Microsoft Project - instalka

### ISSUE THREAD

**Issue by SemionPar** [SemionPar/application.allegro#2]
Prośba do kogoś z was kto ma konto na msdn - ściągnijcie i udostępnijcie proszę ten soft - trzeba przynieść zrobiony harmonogram na następny wykład z Inżynierii.

**Comment by MichalPi** [comment]
ftp://michal.no-ip.pl/downloads/pl_project_professional_2013_x86_and_x64_dvd_1353484.iso
 Tu wrzucilem wersje 2013. Jak to sciąganie ledwo idzie to mowcie

**Comment by MichalPi** [comment]
Też patrze ze tu coś sie znajdzie https://thepiratebay.se/search/microsoft%20project/0/7/0

**Comment by SemionPar** [comment]
Dzięki wielkie, do czwartku zrobimy ten harmonogram, dziś postaram się już ty wszystko poumieszczać
