### ISSUE TITLE
Pilne - konto allegro

### ISSUE THREAD

**Issue by MichalPi** [SemionPar/application.allegro#6]
Ma ktoś konto allegro, ktore moglby bez problemu udostepnic? Jest potrzebne do projektu, takie wspolne konto. Ja korzystam jedynie z konta mojego taty i lipa tutaj uploadować dane, zeby wszyscy znali (login i hasło). A konto potrzebne jest do wygenerowania klucza allegro webapi. Jak ktoś ma mało używane konto allegro to by było fajnie jakby podal dane....

**Comment by SemionPar** [comment]
ja mam podobnie, bo cały czas korzystam z konta rodziców... przyłączam się do prośby, macie może jakieś swoje aktywowane konto?

**Comment by MichalPi** [comment]
Dobra, ja już założyłem na siebie konto udało mi się je aktywować. Tylko nie kupujcie nic na tym koncie na mnie bo usune :D
Tutaj dane wpisalem w klasie:
https://github.com/SemionPar/application.allegro/blob/Michal/api/src/main/java/projekt/api/Constans.java
